im:
  tcpPort: 9000
  webSocketPort: 8082
  boosThreadSize: 1
  workThreadSize: 8
  heartBeatTime: 20000
  brokerId: 1001
  loginModel: 1
  logicUrl: http://127.0.0.1:8000/v1

  redis:
    mode: single
    database: 0
    password:
    timeout: 3000
    poolMinIdle: 8
    poolConnTimeout: 3000
    poolSize: 10
    host: 127.0.0.1:6379

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtualHost: /
    userName: admin
    password: pass.123

  zkConfig:
    zkAddr: 127.0.0.1:2181
    zkConnectTimeOut: 5000
    sessionTimeoutMs: 5000



