


spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password:
    url: jdbc:mysql://127.0.0.1:3306/im-core?serverTimezone=UTC&useSSL=false&characterEncoding=UTF8
    username: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: UTC
  application:
    name: im-system

logging:
  config: classpath:logback-spring.xml

server:
  port: 8000